import { createTheme } from '@mui/material/styles';
import { c, radius, shadow, ease } from '@shared/design/tokens';

export const theme = createTheme({
  palette: {
    mode: 'light', primary: { main: c.primary, dark: c.primaryHover, light: c.primaryContainer, contrastText: c.onPrimary },
    secondary: { main: c.inverse, contrastText: c.onInverse }, success: { main: c.successInk, light: c.success, contrastText: c.onSuccess },
    warning: { main: c.primaryIcon, light: c.primaryContainer, contrastText: c.onPrimaryContainer },
    error: { main: c.error, light: c.errorContainer, contrastText: c.onErrorContainer }, info: { main: c.primaryInk },
    background: { default: c.surface, paper: c.surfaceCard }, text: { primary: c.ink, secondary: c.inkMuted, disabled: c.inkFaint }, divider: c.outline,
  },
  shape: { borderRadius: radius.field },
  typography: {
    fontFamily: "Figtree, 'Manrope Variable', Manrope, system-ui, sans-serif",
    allVariants: { fontOpticalSizing: 'auto' },
    h1: { fontWeight: 700, letterSpacing: '-0.035em', lineHeight: 1.06 },
    h2: { fontWeight: 700, letterSpacing: '-0.03em', lineHeight: 1.08 },
    h3: { fontWeight: 700, letterSpacing: '-0.03em', lineHeight: 1.1 },
    h4: { fontWeight: 700, letterSpacing: '-0.025em' },
    h5: { fontSize: 22, fontWeight: 700, letterSpacing: '-0.02em' },
    h6: { fontSize: 18, fontWeight: 700, letterSpacing: '-0.01em' },
    subtitle1: { fontWeight: 700, letterSpacing: '-0.01em' }, subtitle2: { fontWeight: 600 },
    body1: { fontSize: 15, lineHeight: 1.55 }, body2: { fontSize: 13, lineHeight: 1.5 }, caption: { fontSize: 12 },
    button: { textTransform: 'none', fontWeight: 600, letterSpacing: 0 },
    overline: { fontWeight: 700, letterSpacing: '.09em', fontSize: 11, lineHeight: 1.4, color: c.inkFaint },
  },
  components: {
    MuiCssBaseline: { styleOverrides: { body: { backgroundColor: c.surface, color: c.ink } } },
    MuiPaper: { styleOverrides: { root: { backgroundImage: 'none' } } },
    MuiCard: { defaultProps: { elevation: 0 }, styleOverrides: { root: { borderRadius: radius.card, border: `1px solid ${c.outline}`, background: c.surfaceCard } } },
    MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: { root: { borderRadius: radius.pill, height: 48, paddingInline: 24, fontSize: 15, transition: `transform 120ms ${ease}, background-color 180ms ${ease}`, '&:active': { transform: 'scale(.97)' } }, sizeSmall: { height: 40, paddingInline: 18, fontSize: 13 }, sizeLarge: { height: 56, paddingInline: 28, fontSize: 16 }, contained: { boxShadow: shadow.raised, '&:hover': { boxShadow: '0 3px 10px rgba(60,50,10,.18)' } }, outlined: { borderColor: c.outlineStrong, color: c.onPrimary, '&:hover': { borderColor: c.outlineStrong, background: 'rgba(36,26,0,.05)' } }, text: { color: c.primaryInk, '&:hover': { background: c.surfaceField } } } },
    MuiIconButton: { styleOverrides: { root: { color: c.inkMuted, transition: `transform 120ms ${ease}, background 180ms ${ease}`, '&:hover': { background: c.surfaceField }, '&:active': { transform: 'scale(.92)' } } } },
    MuiChip: { styleOverrides: { root: { fontWeight: 600, borderRadius: radius.chip }, outlined: { borderColor: c.outline } } },
    MuiTabs: { styleOverrides: { root: { minHeight: 0, borderBottom: `1px solid ${c.outline}` }, indicator: { height: 3, borderRadius: '3px 3px 0 0', background: c.accent } } },
    MuiTab: { styleOverrides: { root: { textTransform: 'none', fontWeight: 600, fontSize: 14, minHeight: 54, padding: '16px 20px', color: c.inkMuted, '&.Mui-selected': { color: c.ink } } } },
    MuiTooltip: { defaultProps: { arrow: true }, styleOverrides: { tooltip: { background: c.inverseSurface, color: c.onInverseSurface, fontSize: 12 }, arrow: { color: c.inverseSurface } } },
    MuiDivider: { styleOverrides: { root: { borderColor: c.outline } } },
    MuiLinearProgress: { styleOverrides: { root: { height: 8, borderRadius: 4, background: c.track }, bar: { borderRadius: 4, background: c.accent } } },
    MuiDialog: { styleOverrides: { paper: { borderRadius: radius.panel, background: c.surface, boxShadow: shadow.dialog, padding: 4 } } },
    MuiSnackbarContent: { styleOverrides: { root: { borderRadius: radius.tile, background: c.inverseSurface, color: c.onInverseSurface, boxShadow: shadow.snack } } },
    MuiListItemButton: { styleOverrides: { root: { borderRadius: radius.row } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: radius.tile }, standardError: { background: c.errorContainer, color: c.errorInk }, standardSuccess: { background: c.success, color: c.successInk }, standardWarning: { background: c.primaryContainer, color: c.onPrimaryContainer } } },
    MuiTextField: { defaultProps: { variant: 'filled' } },
    MuiOutlinedInput: { styleOverrides: { root: { borderRadius: radius.chip, background: c.surfaceCard } } },
    MuiFilledInput: { defaultProps: { disableUnderline: false }, styleOverrides: { root: { borderRadius: `${radius.field}px ${radius.field}px 4px 4px`, background: c.surfaceField, '&:hover': { background: '#EFE6D0' }, '&.Mui-focused': { background: c.surfaceFieldHover }, '&:before': { borderBottom: `2px solid ${c.outlineField}` }, '&:after': { borderBottom: `2px solid ${c.accent}` } }, input: { fontSize: 16 } } },
    MuiInputLabel: { styleOverrides: { root: { color: c.inkMuted, '&.Mui-focused': { color: c.primary } } } },
    MuiCheckbox: { styleOverrides: { root: { color: c.outlineField, '&.Mui-checked': { color: c.primary } } } },
    MuiRadio: { styleOverrides: { root: { color: c.outlineField, '&.Mui-checked': { color: c.primary } } } },
    MuiRating: { styleOverrides: { iconFilled: { color: c.primary } } },
    MuiAccordion: { styleOverrides: { root: { background: 'transparent' } } },
    MuiAvatar: { styleOverrides: { root: { fontWeight: 700, fontSize: 14 } } },
  },
});
